on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Packages
        run: dotnet restore
      - name: Clean
        run: |
          rm -rf modweaver.*/obj
      - name: Copy NuGet packages because nuget is stoopid
        run: |
          cp -r ~/.nuget/packages packages
          ls packages
          echo "SPIDERHECK GAMELIBS/lib"
          ls packages/spiderheck.gamelibs
      - name: Build Project
        uses: cake-build/cake-action@v2.0.0
        with:
          target: Build
          arguments: |
            clean
            nologo
            
      - name: Copy Files
        run: |
          pwd
          ls bin
          mkdir .temp-files
          mkdir .temp-files/modweaver
          mkdir .temp-files/modweaver/libs
          mkdir .temp-files/modweaver/mods
          echo "${{ github.ref_name }}:${{ github.sha }}" > .temp-files/.modweaver_version_do_not_touch
          tree .temp-files
          echo "Begin copying files to artifact dir"
          cp ./bin/0Harmony.dll .temp-files/modweaver/libs
          cp ./bin/modweaver.core.dll .temp-files/modweaver/libs
          cp ./bin/modweaver.preload.dll .temp-files/modweaver/libs
          cp ./bin/Mono.Cecil.dll .temp-files/modweaver/libs
          cp ./bin/Mono.Cecil.Mdb.dll .temp-files/modweaver/libs
          cp ./bin/Mono.Cecil.Pdb.dll .temp-files/modweaver/libs
          cp ./bin/Mono.Cecil.Rocks.dll .temp-files/modweaver/libs
          cp ./bin/MonoMod.RuntimeDetour.dll .temp-files/modweaver/libs
          cp ./bin/MonoMod.Utils.dll .temp-files/modweaver/libs
          cp ./bin/Newtonsoft.Json.dll .temp-files/modweaver/libs
          cp ./bin/NLog.dll .temp-files/modweaver/libs
          cp ./bin/Tomlyn.dll .temp-files/modweaver/libs
          cp ./bin/RestSharp.dll .temp-files/modweaver/libs
          cp ./bin/System.Net.Http.dll .temp-files/modweaver/libs
          cp ./doorstop/* .temp-files/
          echo "Done"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Modweaver ZIP
          path: .temp-files
